# Generated by Django 3.2.9 on 2021-12-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockclose',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockdetails'),
        ),
        migrations.AlterField(
            model_name='stockhigh',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockdetails'),
        ),
        migrations.AlterField(
            model_name='stocklow',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockdetails'),
        ),
        migrations.AlterField(
            model_name='stockopen',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockdetails'),
        ),
        migrations.AlterField(
            model_name='stockvolume',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockdetails'),
        ),
    ]
